# Site settings
## Change the values as needed.
title: wrathsoffire76's blog
email: 
description: "Welcome to my testing blog and other stuff zzzzzzzzzz...."
keywords: "blog, material, wrathsoffire76, Nintendo, hacking"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "https://wrathsoffire76-blog.github.io/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  twitter: wrathsoffire76
  github: wrathsoffire76
exclude:
  - bower_components
  - README.md

##set this to enable disqus commenting
#disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
